name = "OptimalControl"
uuid = "5f98b655-cc9a-415a-b60e-744165666948"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "1.1.8-beta"

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
CTDirect = "790bbbee-bee9-49ee-8912-a9de031322d5"
CTFlows = "1c39547c-7794-42f7-af83-d98194f657c2"
CTModels = "34c4fa32-2049-4079-8329-de33c2a22e2d"
CTParser = "32681960-a1b1-40db-9bff-a1ca817385d1"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extras]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPMumps = "3b83494e-c0a4-4895-918b-9157a7a085a1"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ADNLPModels = "0.8"
CTBase = "0.16, 0.17"
CTDirect = "0.17"
CTFlows = "0.8"
CTModels = "0.6"
CTParser = "0.7, 0.8"
CommonSolve = "0.2"
DifferentiationInterface = "0.7"
DocStringExtensions = "0.9"
ExaModels = "0.9"
ForwardDiff = "0.10, 1.0"
LinearAlgebra = "1"
MadNLP = "0.8"
MadNLPMumps = "0.5"
NLPModelsIpopt = "0.11"
NonlinearSolve = "4"
OrdinaryDiffEq = "6"
RecipesBase = "1"
SplitApplyCombine = "1"
Test = "1"
julia = "1.10"

[targets]
test = ["DifferentiationInterface", "ForwardDiff", "LinearAlgebra", "MadNLP", "MadNLPMumps", "NLPModelsIpopt", "NonlinearSolve", "OrdinaryDiffEq", "SplitApplyCombine", "Test"]