[deps]
MINPACK = "4854310b-de5a-5eb6-a2a5-c1dee2bd17f9"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
OptimalControl = "0.6"
julia = "1.8"
